name: Build AndUEDumper

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: "25.2.9519653"

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
          unzip -q ndk.zip -d ${{ runner.temp }}
          mkdir -p ${{ runner.temp }}/android-ndk
          mv ${{ runner.temp }}/android-ndk-r25b/* ${{ runner.temp }}/android-ndk/
          rm -rf ${{ runner.temp }}/android-ndk-r25b

      - name: Set NDK_HOME environment variable
        run: echo "NDK_HOME=${{ runner.temp }}/android-ndk" >> $GITHUB_ENV

      - name: Debug NDK folder
        env:
          NDK_HOME: ${{ env.NDK_HOME }}
        run: |
          echo "NDK_HOME=$NDK_HOME"
          ls -l $NDK_HOME

      - name: Build AndUEDumper
        working-directory: AndUEDumper
        env:
          NDK_HOME: ${{ env.NDK_HOME }}
        run: |
          export PATH=$NDK_HOME:$PATH
          make clean
          make

      - name: List built binaries
        working-directory: AndUEDumper
        env:
          NDK_HOME: ${{ env.NDK_HOME }}
        run: ls -l

      ####### Solution 1: Upload specific binary file #######
      # Adjust the path below if your binary name or location is different
      - name: Upload specific binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndUEDumper-binary
          path: AndUEDumper/UEDump3r

      ####### Solution 2: Upload entire build folder #######
      # Uncomment to upload everything inside the AndUEDumper folder
      # - name: Upload entire build directory
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: AndUEDumper-full-build
      #     path: AndUEDumper/**

  release:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts (Solution 1)
        uses: actions/download-artifact@v3
        with:
          name: AndUEDumper-binary
          path: ./release-artifacts

      # Uncomment the following block and comment the above download step
      # if you use Solution 2 artifact upload:
      #
      # - name: Download build artifacts (Solution 2)
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: AndUEDumper-full-build
      #     path: ./release-artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          name: Release ${{ github.sha }}
          body: |
            Automated release created from GitHub Actions build.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./release-artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
